import type { CellularGeometryResult, CellularOpening, WebPost } from "@/core/cellular/models";
import type { DiagramSample } from "@/core/loads";

export type OpeningAction = Readonly<{ openingNumber: number; xM: number; shearN: number; momentNm: number; topTeeAxialN: number; bottomTeeAxialN: number; teeShearN: number; vierendeelMomentDemandNm: number; status: "actionExtracted" }>;
export type WebPostAction = Readonly<{ webPostNumber: number; xM: number; clearWidthM: number; shearN: number; horizontalShearFlowNPerM: number; bendingMomentNm: number; status: "actionExtracted" }>;
export type CellularCheckExtraction = Readonly<{ openings: readonly OpeningAction[]; webPosts: readonly WebPostAction[]; limitations: readonly string[]; extractionVersion: "cellular-action-extraction-1.0.0" }>;
export class CellularCheckError extends Error { public constructor(message: string) { super(message); this.name = "CellularCheckError"; } }

/** Extracts elastic actions only; resistance needs a selected design standard. */
export function extractCellularCheckActions(geometry: CellularGeometryResult, samples: readonly DiagramSample[]): CellularCheckExtraction {
  if (!geometry.isValid) throw new CellularCheckError("Valid cellular geometry is required.");
  if (samples.length < 2) throw new CellularCheckError("At least two diagram samples are required.");
  const teeLeverArmM = getTeeLeverArm(geometry);
  return { openings: geometry.openings.map((opening) => openingAction(opening, samples, teeLeverArmM)), webPosts: geometry.webPosts.map((webPost) => webPostAction(webPost, samples)), limitations: ["Actions are interpolated from the Phase 6 straight-beam elastic analysis samples.", "Vierendeel, tee, web-post, local yielding, buckling, weld, and concentrated-load resistance are not evaluated without a selected standard and applicable equations.", "Opening actions use a symmetric-tee lever arm and are not applicable to eccentric openings."], extractionVersion: "cellular-action-extraction-1.0.0" };
}
function openingAction(opening: CellularOpening, samples: readonly DiagramSample[], teeLeverArmM: number): OpeningAction { const action = interpolate(samples, opening.centerXM); const moment = Math.abs(action.momentNm); const shear = Math.abs(action.shearN); return { openingNumber: opening.number, xM: opening.centerXM, shearN: action.shearN, momentNm: action.momentNm, topTeeAxialN: moment / teeLeverArmM, bottomTeeAxialN: moment / teeLeverArmM, teeShearN: shear / 2, vierendeelMomentDemandNm: shear * opening.diameterM / 4, status: "actionExtracted" }; }
function webPostAction(webPost: WebPost, samples: readonly DiagramSample[]): WebPostAction { const action = interpolate(samples, webPost.centerXM); return { webPostNumber: webPost.number, xM: webPost.centerXM, clearWidthM: webPost.clearWidthM, shearN: action.shearN, horizontalShearFlowNPerM: Math.abs(action.shearN) / webPost.clearWidthM, bendingMomentNm: action.momentNm, status: "actionExtracted" }; }
function getTeeLeverArm(geometry: CellularGeometryResult): number { const leverArm = geometry.finishedDepthM - geometry.bottomTee.centroidFromOuterFaceM - geometry.topTee.centroidFromOuterFaceM; if (!Number.isFinite(leverArm) || leverArm <= 0) throw new CellularCheckError("Tee lever arm must be positive."); return leverArm; }
function interpolate(samples: readonly DiagramSample[], xM: number): DiagramSample { const sorted = [...samples].sort((a, b) => a.xM - b.xM); const first = sorted[0]; const last = sorted.at(-1); if (!first || !last || xM < first.xM || xM > last.xM) throw new CellularCheckError("Action location lies outside the analysis span."); const rightIndex = sorted.findIndex((sample) => sample.xM >= xM); const right = sorted[rightIndex]; if (!right) return last; if (right.xM === xM || rightIndex === 0) return right; const left = sorted[rightIndex - 1]; if (!left) return right; const ratio = (xM - left.xM) / (right.xM - left.xM); return { xM, axialN: lerp(left.axialN, right.axialN, ratio), shearN: lerp(left.shearN, right.shearN, ratio), momentNm: lerp(left.momentNm, right.momentNm, ratio), deflectionM: lerp(left.deflectionM, right.deflectionM, ratio), rotationRad: lerp(left.rotationRad, right.rotationRad, ratio) }; }
function lerp(left: number, right: number, ratio: number): number { return left + (right - left) * ratio; }
