import { z } from "zod";

const requiredText = z.string().trim().min(1);
export const projectSettingsSchema = z.object({
  projectId: requiredText,
  organizationId: requiredText,
  general: z.object({
    name: requiredText,
    number: requiredText,
    client: z.string().trim(),
    owner: z.string().trim(),
    siteLocation: z.string().trim(),
    buildingType: z.string().trim(),
    designer: z.string().trim(),
    checker: z.string().trim(),
    approver: z.string().trim(),
    revision: requiredText,
    calculationDateIso: z.iso.date(),
    notes: z.string().max(5000),
  }),
  standards: z.object({
    country: z.enum(["TH", "US", "EU"]),
    primaryCode: requiredText,
    secondaryGuidance: z.string(),
    designMethod: z.enum(["LRFD", "ASD", "EUROCODE"]),
    standardEdition: requiredText,
    loadStandard: requiredText,
    steelStandard: requiredText,
    weldingStandard: requiredText,
    reportLanguage: z.enum(["th", "en", "bilingual"]),
  }),
  materials: z.object({
    steelGrade: requiredText,
    weldElectrode: requiredText,
    boltGrade: z.string(),
    concreteGrade: z.string(),
    steelDensity: z.object({ value: z.number().positive(), unit: z.literal("kg/m³") }),
    corrosionAllowance: z.object({ value: z.number().min(0), unit: z.literal("mm") }),
    temperature: z.object({ value: z.number(), unit: z.literal("°C") }),
  }),
  analysis: z.object({
    analysisOrder: z.enum(["firstOrder", "secondOrder"]),
    elementFormulation: z.enum(["eulerBernoulli", "timoshenko"]),
    solverTolerance: z.number().positive().max(0.01),
    convergenceTolerance: z.number().positive().max(0.01),
    includeShearDeformation: z.boolean(),
    includeSelfWeight: z.boolean(),
  }),
  design: z.object({
    method: z.enum(["LRFD", "ASD", "EUROCODE"]),
    unbracedLength: z.object({ value: z.number().nonnegative(), unit: z.literal("m") }),
    effectiveLengthFactor: z.number().positive(),
    deflectionLimitRatio: z.number().int().positive(),
    designLifeYears: z.number().int().positive(),
    exposureCondition: z.string(),
  }),
  units: z.object({
    profile: z.enum(["thaiEngineeringMetric", "siEngineering"]),
    significantFigures: z.number().int().min(2).max(8),
    decimalSeparator: z.enum([".", ","]),
    thousandsSeparator: z.enum([",", ".", " "]),
  }),
  report: z.object({
    companyName: z.string(),
    address: z.string(),
    engineerName: z.string(),
    licenseNumber: z.string(),
    reportTitle: requiredText,
    confidentiality: z.enum(["public", "internal", "confidential"]),
  }),
  updatedAtIso: z.iso.datetime(),
  updatedBy: requiredText,
});
export type ProjectSettingsInput = z.input<typeof projectSettingsSchema>;
